all:state_sort state_search clear_state
state_sort:
	gcc -Wall -Werror -Wextra state_sort.c filework.c -o ../build/Quest_1
state_search:
	gcc -Wall -Werror -Wextra state_search.c filework.c -o ../build/Quest_2
clear_state:
	gcc -Wall -Werror -Wextra clear_state.c filework.c -o ../build/Quest_1